// Chrollo query processing — tokenization, stopword filtering, and
// distinctive-term extraction for ripgrep. Pure: no I/O, no state.
//
// Deliberately NOT here anymore: stemming and the trigram typo fallback.
// rg -F substring matches already catches inflections of the literal term,
// and a typo fallback was a layer of compensation over the search engine.

// Stopwords trimmed (no "remember", "talked", "thing" — those carry no signal).
export const STOP_WORDS = new Set([
  "the",
  "a",
  "an",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "do",
  "does",
  "did",
  "will",
  "would",
  "could",
  "should",
  "may",
  "might",
  "shall",
  "can",
  "need",
  "dare",
  "ought",
  "used",
  "to",
  "of",
  "in",
  "for",
  "on",
  "with",
  "at",
  "by",
  "from",
  "as",
  "into",
  "through",
  "during",
  "before",
  "after",
  "above",
  "below",
  "between",
  "out",
  "off",
  "over",
  "under",
  "again",
  "further",
  "then",
  "once",
  "here",
  "there",
  "when",
  "where",
  "why",
  "how",
  "all",
  "both",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "so",
  "than",
  "too",
  "very",
  "just",
  "because",
  "but",
  "and",
  "or",
  "if",
  "while",
  "about",
  "up",
  "down",
  "what",
  "which",
  "who",
  "whom",
  "this",
  "that",
  "these",
  "those",
  "i",
  "me",
  "my",
  "myself",
  "we",
  "our",
  "ours",
  "ourselves",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "her",
  "hers",
  "herself",
  "it",
  "its",
  "itself",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "also",
  "get",
  "got",
  "like",
  "know",
  "think",
  "want",
  "look",
  "use",
  "find",
  "give",
  "tell",
  "say",
  "said",
  "take",
  "come",
  "make",
  "go",
  "see",
]);

// Split code identifiers (camelCase / snake_case / kebab / acronyms), lowercase,
// drop fragments <= 2 chars. Splitting identifiers recovers recall.
export function tokenize(text: string): string[] {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/[_\-\s]+/g, " ")
    .replace(/\W/g, " ")
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter((w) => w.length > 2);
}

// Extract the query's content words: lowercase, non-stopword, bounded for the
// rg pattern count. The user already chose which words matter by typing them.
export function queryTerms(query: string): string[] {
  return tokenize(query)
    .filter((w) => !STOP_WORDS.has(w))
    .slice(0, 8);
}
